### ISSUE TITLE
Data doesn’t agree with that shown on purple air.com map

### ISSUE THREAD

**Issue by chetstone** [finiteloop/air-quality#10]
First of all, thanks for this app. It's very cool. 

In my rural area there is only one sensor within a twenty mile radius, and it consistently reads around twenty points less on your app than the reading shown on the purple air site. Do you know of an explanation? 

Screenshots attached. 

![image](https://user-images.githubusercontent.com/976343/130311654-71823d6e-de29-4285-9115-78dbb5aa4b81.png)

![image](https://user-images.githubusercontent.com/976343/130311671-736491e4-faf3-4d46-aff1-b3db3fca256c.png)

**Comment by bhaggs** [comment]
This is due to that the Air Quality app is providing an AQI reading using the US EPA's conversion formula to more align Purple Air sensor readings with that of how the EPA determines its AQI level.

You can see where the conversion is being applied in the code here:
https://github.com/finiteloop/air-quality/blob/d7be4c7c5afe85223564191e1c947b93e08b5fd9/server/update_data/purpleair.py#L149

**Comment by finiteloop** [comment]
I also updated the app to show a toggle so you can switch between the two readings: https://github.com/finiteloop/air-quality/commit/7df9b5f2b23b3ac97571da167db1d29279df4ded

As @bhaggs said, the measurement that is the default is still what the EPA deems the most actionable / correct based on this research paper: https://cfpub.epa.gov/si/si_public_record_report.cfm?Lab=CEMM&dirEntryId=348236

But I have gotten this question enough, I thought I should provide a toggle.

App Store review is in flight and should be released this weekend.

**Comment by chetstone** [comment]
Thanks 🙏
